[project]
name = "backend"
version = "0.1.0"
description = "Backend do blog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "python-dotenv>=1.2.1",
    "sqlmodel>=0.0.31",
]
